name: device_info_example
description: Demonstrates how to use the device_info plugin.

dependencies:
  flutter:
    sdk: flutter
  device_info:
    path: ../

dev_dependencies:
  test: ^1.3.0
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
